### PR TITLE
Use rollup for build system

### PR DESCRIPTION
**Pull request by paularmstrong**
**Problem:**
As discovered in #78, the build system needs to be updated in order to unlock updating to React v16.x. 

**Solution:** Mostly copies the changes from #76 for rollup. Upgrades babel & mocha.

Using rollup for react-globalize cuts 2.02KB (gzipped) off the production vendor.js file in Twitter Lite 👍 

This will create all of the same formats for builds as #76: cjs, umd, and esm.

### CODE REVIEW

**Comment by paularmstrong** [comment]
FYI: the upgrade to React 16 is ready to go once this is merged: https://github.com/globalizejs/react-globalize/compare/master...paularmstrong:parmstrong/react-16. Once that's done, we could go forward with updating to use more ES6, new eslint/prettier/whatever.

**Comment by rxaviers** [comment]
Thank you.

> Solution: Mostly copies the changes from #76 for rollup. Upgrades babel & mocha.

For that reason, I've cherry-picked the original changes from that branch and applied yours on top of it in an attempt to be the fair to both of you @paularmstrong and @diligiant.

Merged by 8d92b0f4c6fee22fcccdaf75ea22096904361c91 and dd35eb81f3228101a480017c13129aa5d7ecbb19.

**Comment by rxaviers** [comment]
> Using rollup for react-globalize cuts 2.02KB (gzipped) off the production vendor.js file in Twitter Lite :+1:

This is awesome

**Comment by rxaviers** [comment]
> FYI: the upgrade to React 16 is ready to go once this is merged: paularmstrong/react-globalize@1ef481e. Once that's done, we could go forward with updating to use more ES6, new eslint/prettier/whatever.

@paularmstrong please can you submit a PR

**Pull request closed without merging**
