### PR TITLE
Upgrade to support React 16

### PR DESCRIPTION
**Pull request by paularmstrong**

### CODE REVIEW

**Comment by paularmstrong** [comment]
ping @rxaviers

**Comment by rxaviers** [comment]
Hi @paularmstrong, the content of these changes LGTM, but we should give credits to the original author (i.e., #76). I encourage we do something analogous to #79, where I preserved authorship in 8d92b0f4c6fee22fcccdaf75ea22096904361c91 and dd35eb81f3228101a480017c13129aa5d7ecbb19. Cherry-picking the original changes is the main responsible for the delay on my end. Help appreciated. Thanks

**Comment by paularmstrong** [comment]
@diligiant do you care? This seems like a waste of time and resources.

**Comment by diligiant** [comment]
I agree with @paularmstrong : why bother when you can slow down everyone for nothing and later get the credit for doing the work?

**Comment by rxaviers** [comment]
@paularmstrong, as you can see from @diligiant's response above, the "waste of time" is debatable.  Note #76 already had the implementations you are redoing/splitting here plus in #79, but there were [arguments](https://github.com/globalizejs/react-globalize/pull/76#issuecomment-333604012) against merging it, because it was implementing too many things at once and it was ideal to split it. I agreed with such argument despite the fact it slows down the process. Here we are. Now, I cannot ignore the original authorship either.

The resources in this open source project are pretty scarce, I agree. You (@paularmstrong) and @diligiant are bringing valuable contributions to this project and I really wanted us to converge efforts. I am trying to accommodate both interests for that reason.

**Comment by diligiant** [comment]
Of course, that’s your job (maybe your style), not mine (really not ;)

**Comment by rxaviers** [comment]
I acknowledge that in an attempt to accommodate both, I risk accommodating none. 😞

**Comment by necolas** [comment]
Please let's merge this and move on

**Comment by rxaviers** [comment]
Thank you @diligiant and @paularmstrong. This has been merged by 457efe28eca95fbe9f4bac78002513fe490596e8 and 163fbd114cbc2b9f0ae7504049823a63c81977db.

**Pull request closed without merging**
